<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwMH2UV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwMH2UV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFwMH2UV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFwMH2UV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFwMH2UV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FwMH2UV',
    'container.build_id' => 'e62a9e34',
    'container.build_time' => 1563899858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwMH2UV');
