<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSk85gWf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSk85gWf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSk85gWf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSk85gWf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSk85gWf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Sk85gWf',
    'container.build_id' => '6dfe9d9f',
    'container.build_time' => 1563974502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSk85gWf');
